const LRdata = [
    {
      _id: "67762357c35fbff9d54271d0",
      lrNumber: "4567",
      date: "2025-01-02T00:00:00.000Z",
      vehicleNumber: "MH123",
      owner: "HB Gadget",
      consignorName: "Sender Company",
      consignorAddress: "Ahmednagar Industrial Area",
      consigneeName: "Receiver Company",
      consigneeAddress: "Pune Warehouse",
      customer: "ABC Pvt Ltd",
      from: "Ahmednagar",
      to: "Pune",
      driverName: "John Doe",
      driverContact: "9876543210",
      containerNumber: "CONT12345",
      sealNumber: "SEAL5678",
      itemName: "Wood",
      quantity: 4,
      unit: "ton",
      actualWeight: 19,
      chargedWeight: 25,
      customerRate: 2000,
      totalAmount: 50000,
      transporterRate: 50,
      totalTransporterAmount: 2500,
      transporterRateOn: "ton",
      customerRateOn: "ton",
      customerFreight: 456,
      transporterFreight: 456,
      __v: 0,
    },
    {
      _id: "67762357c35fbff9d54271d1",
      lrNumber: "5678",
      date: "2025-01-03T00:00:00.000Z",
      vehicleNumber: "MH456",
      owner: "XYZ Logistics",
      consignorName: "Steel Suppliers",
      consignorAddress: "Mumbai Industrial Zone",
      consigneeName: "Metal Traders",
      consigneeAddress: "Nagpur Industrial Area",
      customer: "DEF Corporation",
      from: "Mumbai",
      to: "Nagpur",
      driverName: "Rahul Sharma",
      driverContact: "9876532100",
      containerNumber: "CONT78901",
      sealNumber: "SEAL1234",
      itemName: "Steel Sheets",
      quantity: 8,
      unit: "ton",
      actualWeight: 30,
      chargedWeight: 32,
      customerRate: 2500,
      totalAmount: 80000,
      transporterRate: 60,
      totalTransporterAmount: 3840,
      transporterRateOn: "ton",
      customerRateOn: "ton",
      customerFreight: 600,
      transporterFreight: 550,
      __v: 0,
    },
    {
      _id: "67762357c35fbff9d54271d2",
      lrNumber: "6789",
      date: "2025-01-04T00:00:00.000Z",
      vehicleNumber: "MH789",
      owner: "Alpha Transport",
      consignorName: "Agri Goods",
      consignorAddress: "Nashik Market Yard",
      consigneeName: "Food Processors Ltd",
      consigneeAddress: "Aurangabad Plant",
      customer: "Agri Pvt Ltd",
      from: "Nashik",
      to: "Aurangabad",
      driverName: "Manoj Kumar",
      driverContact: "9876521340",
      containerNumber: "CONT54321",
      sealNumber: "SEAL9876",
      itemName: "Wheat",
      quantity: 15,
      unit: "ton",
      actualWeight: 28,
      chargedWeight: 30,
      customerRate: 1500,
      totalAmount: 45000,
      transporterRate: 55,
      totalTransporterAmount: 1650,
      transporterRateOn: "ton",
      customerRateOn: "ton",
      customerFreight: 500,
      transporterFreight: 480,
      __v: 0,
    },
    {
      _id: "67762357c35fbff9d54271d3",
      lrNumber: "7890",
      date: "2025-01-05T00:00:00.000Z",
      vehicleNumber: "MH321",
      owner: "Delta Movers",
      consignorName: "Chemical Corp",
      consignorAddress: "Thane Industrial Area",
      consigneeName: "Paint Manufacturers",
      consigneeAddress: "Kolhapur Factory",
      customer: "Chemicals Ltd",
      from: "Thane",
      to: "Kolhapur",
      driverName: "Suresh Naik",
      driverContact: "9876501234",
      containerNumber: "CONT67890",
      sealNumber: "SEAL3456",
      itemName: "Chemical Drums",
      quantity: 20,
      unit: "ton",
      actualWeight: 50,
      chargedWeight: 55,
      customerRate: 3000,
      totalAmount: 165000,
      transporterRate: 80,
      totalTransporterAmount: 4400,
      transporterRateOn: "ton",
      customerRateOn: "ton",
      customerFreight: 800,
      transporterFreight: 750,
      __v: 0,
    },
  ];
  
  export default LRdata;
  