export const tyreMange = () => [
  {
    id: 1,
    serialNumber: 'TYR12345',
    vendor: 'Goodyear',
    purchaseDate: '2024-03-15',
    status: 'New',
    distance: 12000,
    size: '18',
    brand: 'MRF',
    pressure: '35psi',
    treadDepth: '10mm',
    pattern: 'Radial',
    document: 'document-link-1.pdf',
    assignedToVehicle: 'MH34522',
    wheelPosition: 'Front-Left',
  },
  {
    id: 2,
    serialNumber: 'TYR12346',
    vendor: 'Michelin',
    brand: 'MRF',
    pattern: 'Radial',
    size: '18',
    treadDepth: '10mm',
    pressure: '35psi',
    purchaseDate: '2023-08-10',
    status: 'In Use',
    distance: 25000,
    document: 'document-link-2.pdf',
    assignedToVehicle: 'MH45697',
    wheelPosition: 'Front-Right',
  },
  {
    id: 3,
    serialNumber: 'TYR12347',
    vendor: 'Pirelli',
    brand: 'MRF',
    pattern: 'Radial',
    size: '18',
    treadDepth: '10mm',
    pressure: '35psi',
    purchaseDate: '2023-01-20',
    status: 'Needs Replacement',
    distance: 30000,
    document: 'document-link-3.pdf',
    assignedToVehicle: 'MH23476',
    wheelPosition: 'Rear-Right',
  },
  {
    id: 4,
    serialNumber: 'TYR12348',
    vendor: 'Pirelli',
    brand: 'MRF',
    pattern: 'Radial',
    size: '18',
    treadDepth: '10mm',
    pressure: '35psi',
    purchaseDate: '2023-01-20',
    status: 'Needs Replacement',
    distance: 30000,
    document: 'document-link-3.pdf',
    assignedToVehicle: 'MH45675',
    wheelPosition: 'Rear-Left',
  },
  {
    id: 5,
    serialNumber: 'TYR12350',
    vendor: 'Pirelli',
    brand: 'MRF',
    pattern: 'Radial',
    size: '18',
    treadDepth: '10mm',
    pressure: '35psi',
    purchaseDate: '2023-01-20',
    status: 'Needs Replacement',
    distance: 30000,
    document: 'document-link-3.pdf',
    assignedToVehicle: 'MH45675',
    wheelPosition: 'Rear-Left',
  },
]
